version: '3.2'
services:

  client:
    build: ./client
    ports:
      - 8080:80

  server:
    build: ./server
    ports:
      - 3000:3000

  mysql:
    image: bitnami/mysql:8.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
